### ISSUE TITLE
The SDK should support computer audio on safari 11

### ISSUE THREAD

**Issue by pai911** [zoom/sample-app-web#11]
We cannot join by computer audio on Safari 11 with current JS SDK.

I think it's a bug.

if I fake the user agent of Safari 11 to Chrome, it works perfectly !

I think the JS SDK just disable joining from computer audio for Safari, but the correct way should be detecting the capability of the browser ...

**Comment by michaelZoomDA** [comment]
Hi @pai911, 

Currently we do not support VoIP with Safari, Edge, or Firefox. The reason is because those browsers have an audio processing bug when the browser gets busy, so that will impact the audio quality of VoIP. 
However, those browsers can still use dial in by phone for the audio option.

**Comment by pai911** [comment]
Hi @michaelZoomDA 

Thank you for the response.

But if this is the case, then why does the zoom official web client can support VOIP with Safari ?

The official web client has the URL pattern like this ..

https://zoom.us/wc/3109894843/start

**Comment by michaelZoomDA** [comment]
Hi @pai911, 

The Web client shouldn't support VOIP. If you are seeing this, can you provide a screenshot?

Thanks
